'use strict';

var mongoose = require('mongoose');
var ObjectId = mongoose.Types.ObjectId;

let sharedId= ObjectId()
let sharedId2 = ObjectId()

var users = {
  name : 'User',
  data : [
    {
      "_id"          : ObjectId(),
      "firstName"    : "Masiar",
      "lastName"     : "Babazadeh",
      "userName"     : "masiar",
      "email"        : "masiar.babazadeh@usi.ch",
      "password"     : "ciao",
      "freelancers":  [sharedId,sharedId2],
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },

    {
      "_id"          : ObjectId(),
      "firstName"    : "Robert",
      "lastName"     : "Sapolsky",
      "userName"     : "rob",
      "email"        : "sapolsky@stanford.edu",
      "password"     : "baboon",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },
    {
      "_id"          : ObjectId(),
      "firstName"    : "Simon",
      "lastName"     : "Reding",
      "userName"     : "simon",
      "email"        : "sapolsky@stanford.edu",
      "password"     : " ",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },
    {
      "_id"          : ObjectId(),
      "firstName"    : "Alexander",
      "lastName"     : "Camenzind",
      "userName"     : "alex",
      "email"        : "sapolsky@stanford.edu",
      "password"     : " ",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },
    {
      "_id"          : ObjectId(),
      "firstName"    : "Paolo",
      "lastName"     : "Falconi",
      "userName"     : "paolo",
      "email"        : "sapolsky@stanford.edu",
      "password"     : " ",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },
    {
      "_id"          : ObjectId(),
      "firstName"    : "Andrea",
      "lastName"     : "Peroziello",
      "userName"     : "andrea",
      "email"        : "sapolsky@stanford.edu",
      "password"     : " ",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },
    {
      "_id"          : ObjectId(),
      "firstName"    : "Gianmarco",
      "lastName"     : "Palazzi",
      "userName"     : "gianmarco",
      "email"        : "sapolsky@stanford.edu",
      "password"     : " ",
      "dateCreated"  : "Sat Sep 27 2014 10:26:46 GMT+0200 (CEST)",
      "emailVerification" : "true",
    },

    {
      "_id"          : ObjectId(),
      "firstName"    : "Vasileios",
      "lastName"     : "Triglianos",
      "userName"     : "vassilis",
      "email"        : "vasileios.triglianos@usi.ch",
      "password"     : "ciao",
      "dateCreated"  : "Sat Sep 27 2014 10:28:21 GMT+0200 (CEST)",
      "emailVerification" : "true",
    }
  ]
}

var freelancers={
  name:"Freelancer",
  data:[
  {
    "_id":sharedId,
    "firstName": "Masiar",
    "lastName":"Babazadeh",
    "email":"peter_s@gmail.com",
    "location":"Lugano",
    "latitude": "46.0058",
    "longitude": "8.9475",
    "job":"Carpenter",
    "telephoneNum":"+41793234143",
    "description":"Best carpenter around!",
    "website":"ma-carpentingservices.com",
    "skypeAcc":"ma-carpenting",
    "country":"Switzerland",
    "streetNum":"12",
    "street":"via Buffi",
    "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
    "verified" : "false",
    "emailVerification" : "true",
},
{
  "_id":sharedId2,
  "firstName": "Masiar",
  "lastName":"Babazadeh",
  "email":"peter_s@gmail.com",
  "location":"Lugano",
  "latitude": "46.0058",
  "longitude": "8.9475",
  "job":"Janitor",
  "telephoneNum":"+41793214309",
  "description":"Best in Town. I have great expericence.",
  "website":"ma-janitorservices.com",
  "skypeAcc":"ma-janitor",
  "country":"Switzerland",
  "streetNum":"12",
  "street":"via Buffi",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "verified" : "false",
  "emailVerification" : "true",
},
{
  "_id":ObjectId(),
  "firstName": "Bob",
  "lastName":"Andrews",
  "email":"Bob@gmail.com",
  "location":"Mendrisio",
  "latitude": "45.8667",
  "longitude": "8.9833",
  "job":"Carpenter",
  "telephoneNum":"+41793214343",
  "description":"Great skills. Over 10 years of expericence in the field.",
  "website":"andrewthecarpenter.com",
  "skypeAcc":"andy",
  "country":"Switzerland",
  "streetNum":"12",
  "street":"via Buffi",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "verified" : "false",
  "emailVerification" : "true",
},
{
  "_id":ObjectId(),
  "firstName": "Justus",
  "lastName":"Jonas",
  "email":"Justus@gmail.com",
  "location":"Lugano",
  "latitude": "46.0058",
  "longitude": "8.9475",
  "job":"Janitor",
  "telephoneNum":"+41793219923",
  "description":"Extremely experienced. 100% Satisfaction guaranteed!",
  "website":"janitor-justus.com",
  "skypeAcc":"j.jonas",
  "country":"Switzerland",
  "streetNum":"12",
  "street":"via Buffi",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "verified" : "false",
  "emailVerification" : "true",
},
{
  "_id":ObjectId(),
  "firstName": "Peter",
  "lastName":"Parker",
  "email":"Peter_p@gmail.com",
  "location":"Bellinzona",
  "latitude": "46.2",
  "longitude": "9.0167",
  "job":"Carpenter",
  "telephoneNum":"+41791224943",
  "description":"I hit every nail on the head.",
  "website":"www.parker-carpenting.com",
  "skypeAcc":"parkerCarpenting",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "country":"Switzerland",
  "streetNum":"12",
  "street":"via Buffi",
  "verified" : "false",
  "emailVerification" : "true",
},
{
  "_id":ObjectId(),
  "firstName": "Carl Wilibald",
  "lastName":"Parker",
  "email":"carl_p@gmail.com",
  "location":"Bellinzona",
  "latitude": "46.2",
  "longitude": "9.0167",
  "job":"Carpenter",
  "telephoneNum":"+41793213443",
  "description":"I can work really well and fast. ",
  "website":"parker-bellinzona.com",
  "skypeAcc":"carl_Parker",
  "country":"Switzerland",
  "streetNum":"13",
  "street":"via Buffi",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "verified" : "false",
  "emailVerification" : "true",
},
{
  "_id":ObjectId(),
  "firstName": "Peter",
  "lastName":"Parker",
  "email":"Peter_p@gmail.com",
  "location":"Milano",
  "latitude": "46.2",
  "longitude": "9.0167",
  "job":"Carpenter",
  "telephoneNum":"123",
  "description":"I get the job done!",
  "website":"pete-the-carpenter.com",
  "skypeAcc":"petersParker",
  "country":"Switzerland",
  "streetNum":"12",
  "street":"via Buffi",
  "facebook" :"https:\/\/www.facebook.com/gianmarco.palazzi19",
  "verified" : "true",
  "emailVerification" : "true",
}
]
}

var admins = {
  name : 'Admin',
  data : [
    {
      "userName" : "admin",
      "password" : "admin",
      "email" : "admin@usi.ch",
    }
  ]
}

var seedData = [];
seedData.push(freelancers);
seedData.push(users);

seedData.push(admins);

module.exports = seedData;
